---

- name: Create group
  group:
    name: '{{ phpmyadmin_group }}'
    state: present

- name: Create user
  user:
    name: '{{ phpmyadmin_user }}'
    group: '{{ phpmyadmin_group }}'
    state: present

- name: Ensurce working dir exists
  file:
    path: '{{ phpmyadmin_working_dir }}'
    state: directory

- name: Unarchive file
  register: phpmyadmin_extract
  unarchive:
    src: '{{ phpmyadmin_download_url }}'
    dest: '{{ phpmyadmin_working_dir }}'
    copy: no
    owner: '{{ phpmyadmin_user }}'
    group: '{{ phpmyadmin_group }}'
    mode: '0755'
    creates: '{{ phpmyadmin_working_dir }}/{{ phpmyadmin_unarchiv_dir }}'
    validate_certs: no

- name: Ensure setup dir is absent
  file:
    path: '{{ phpmyadmin_working_dir }}/{{ phpmyadmin_unarchiv_dir }}/setup'
    state: absent

- name: prepare directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ phpmyadmin_user }}'
    group: '{{ phpmyadmin_group }}'
    mode: '0711'
  with_items:
    - '{{ phpmyadmin_working_dir }}'
    - '{{ phpmyadmin_working_dir }}/logs'
    - '{{ phpmyadmin_working_dir }}/sessions'
    - '{{ phpmyadmin_working_dir }}/usr/share/'

- name: prepare directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ phpmyadmin_user }}'
    group: '{{ phpmyadmin_group }}'
    mode: '0777'
  with_items:
    - '{{ phpmyadmin_working_dir }}/tmp'

- name: copy timezone to working_dir
  command: cp -rf /usr/share/zoneinfo {{ phpmyadmin_working_dir }}/usr/share/
  args:
    creates: '{{ phpmyadmin_working_dir }}/usr/share/zoneinfo'

- name: Ensure config directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /etc/php5/fpm/pool.d
    - /etc/nginx/conf.d
    - '{{ phpmyadmin_working_dir }}/dev'

- name: copy dev to working_dir
  command: cp -a /dev/zero /dev/urandom /dev/null {{ phpmyadmin_working_dir }}/dev/
  args:
    creates: '{{ phpmyadmin_working_dir }}/dev/urandom'
